### ISSUE TITLE
Visualization of longer alleles

### ISSUE THREAD

**Issue by JelenaPopovic88** [Illumina/GraphAlignmentViewer#6] opened 2019-08-13 21:34 UTC
Hi,

I have been using your tool to visualize BAM files produced by Expansion Hunter.
For most BAM files produced by Expansion Hunter visualization works fine. But in some cases, I noticed that GraphAlignmentViewer is not showing full allele length predicted by Expansion Hunter. Can you explain to me what I am doing wrong?
I am running commands --variant_catalog, --read_align and --vcf with appropriate files.
I also tested two more parameters --region_extension_clip_length and --show_insertions, but I still don't get the full length.
Thank you

**Comment by virajbdeshpande** [comment] 2019-08-15 19:02
Hello Jelena,

Thank you for trying GraphAlignmentViewer. I can foresee the case you describe happening in 2 situations:
1) GAV infers the graph paths based on the read alignment as opposed to the repeat count reported by EH. If for some reason, the allele reported by EH is longer than the longest allele present in the alignments, then the path length displayed by GAV will be shorter than the full allele length reported by EH.
2) A more specific case of (1) is when the allele length is longer than the read length. In such a situation, the longest path inferred from the alignments will be roughly equal to the read length. This corresponds to the in-repeat reads.

Do you think you are observing something different from the 2 scenarios described above?

Best,
Viraj

**Comment by JelenaPopovic88** [comment] 2019-08-15 19:56
Hi Viraj,

Thanks for your response. 
I am observing the second scenario. Allele reported by EH is longer than the read length. It is a little bit longer than 210 bp and GAV is visualizing around 150 bp.

Best,
Jelena

**Comment by virajbdeshpande** [comment] 2019-08-15 20:03
Ok, that's good to know. I will close the issue now since this is the intended behavior.

**Closed as completed by virajbdeshpande** 2019-08-15 20:03 UTC

**Comment by eberle** [comment] 2019-08-15 20:04
Hi Jalena,

Thanks for using this software. I just wanted to add to add some color here. For a call of 210bp the expectation is that you will have several reads that are fully within the repeat sequence (we call these IRRs). Our goal was to just show all of these reads on top of one another so that users could confirm that the reads supporting the call look reasonable. Particularly, reads in repeats can degrade so the important QC is whether you trust the reads. I hope that this helps.

Cheers,

-Mike

**Comment by JelenaPopovic88** [comment] 2019-08-15 20:18
Hi Mike,

Thanks for the clarification.

Best,
Jelena
